// Premium Kids Products in Indian Rupees
const products = [
    {
        id: 1,
        name: "Adidas Kids Running Shoes",
        category: "Shoes",
        image: "https://images.unsplash.com/photo-1514306688989-be7149c159b1?w=400&h=400&fit=crop",
        price: 3499,
        originalPrice: 5999,
        rating: 4.5,
        reviews: 328,
        description: "Premium Adidas running shoes for kids. Perfect for active kids. Lightweight and comfortable.",
        features: ["Breathable mesh", "Cushioned sole", "Durable rubber", "Available sizes 1-6"],
        inStock: true,
        badge: "Best Seller"
    },
    {
        id: 2,
        name: "Nike Kids T-Shirt",
        category: "Clothing",
        image: "https://images.unsplash.com/photo-1519238263413-b37adc4a9b60?w=400&h=400&fit=crop",
        price: 1299,
        originalPrice: 2499,
        rating: 4.3,
        reviews: 245,
        description: "Comfortable cotton Nike t-shirt for kids. Available in multiple colors.",
        features: ["100% cotton", "Comfortable fit", "Easy to wash", "Sizes 4-14 years"],
        inStock: true,
        badge: "Hot Deal"
    },
    {
        id: 3,
        name: "LEGO Building Blocks Set",
        category: "Toys",
        image: "https://images.unsplash.com/photo-1531305652863-6f3031224c94?w=400&h=400&fit=crop",
        price: 2499,
        originalPrice: 3999,
        rating: 4.8,
        reviews: 412,
        description: "500+ piece LEGO set for creative kids. Develop imagination and creativity.",
        features: ["500+ pieces", "Educational", "Safe for kids", "Includes instruction manual"],
        inStock: true,
        badge: "Best Seller"
    },
    {
        id: 4,
        name: "Kids School Backpack",
        category: "Accessories",
        image: "https://images.unsplash.com/photo-1503387210064-b319f474b50e?w=400&h=400&fit=crop",
        price: 1799,
        originalPrice: 3299,
        rating: 4.6,
        reviews: 389,
        description: "Durable and stylish backpack for school. Waterproof material.",
        features: ["Waterproof", "Multiple compartments", "Ergonomic design", "Lightweight"],
        inStock: true,
        badge: "New"
    },
    {
        id: 5,
        name: "Winter Jacket for Kids",
        category: "Clothing",
        image: "https://images.unsplash.com/photo-1522706323590-d24dbb6b0267?w=400&h=400&fit=crop",
        price: 2999,
        originalPrice: 5499,
        rating: 4.4,
        reviews: 267,
        description: "Warm and stylish winter jacket. Perfect for cold weather.",
        features: ["Warm padding", "Water resistant", "Size range XS-XL", "Multiple colors"],
        inStock: true,
        badge: "Hot Deal"
    },
    {
        id: 6,
        name: "Skateboard for Kids",
        category: "Sports",
        image: "https://images.unsplash.com/photo-1599223557563-430f63602d4e?w=400&h=400&fit=crop",
        price: 2199,
        originalPrice: 4299,
        rating: 4.7,
        reviews: 198,
        description: "Professional skateboard for beginner kids. Safe and durable.",
        features: ["Non-slip deck", "Smooth wheels", "Safety tested", "Includes helmet"],
        inStock: true,
        badge: "New"
    },
    {
        id: 7,
        name: "Kids Roller Skates",
        category: "Sports",
        image: "https://images.unsplash.com/photo-1565043666747-9f2e1c88bb1d?w=400&h=400&fit=crop",
        price: 1899,
        originalPrice: 3499,
        rating: 4.5,
        reviews: 156,
        description: "Adjustable roller skates for kids. Perfect for outdoor fun.",
        features: ["Adjustable size", "Smooth roll", "LED wheels", "Safety gear included"],
        inStock: true,
        badge: null
    },
    {
        id: 8,
        name: "Kids Bicycle Helmet",
        category: "Accessories",
        image: "https://images.unsplash.com/photo-1611339555312-e607c90352fd?w=400&h=400&fit=crop",
        price: 899,
        originalPrice: 1699,
        rating: 4.8,
        reviews: 534,
        description: "Safety-certified bicycle helmet for kids. Lightweight and comfortable.",
        features: ["Safety certified", "Lightweight", "Adjustable strap", "Multiple sizes"],
        inStock: true,
        badge: "Best Seller"
    },
    {
        id: 9,
        name: "Kids Watch (Digital)",
        category: "Accessories",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
        price: 1299,
        originalPrice: 2499,
        rating: 4.2,
        reviews: 276,
        description: "Colorful digital watch for kids. Easy to read and durable.",
        features: ["Water resistant", "Easy to use", "Multiple colors", "Durable band"],
        inStock: true,
        badge: null
    },
    {
        id: 10,
        name: "Kids Art Supply Set",
        category: "Toys",
        image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop",
        price: 699,
        originalPrice: 1299,
        rating: 4.4,
        reviews: 423,
        description: "Complete art supply set. Everything your kid needs to create.",
        features: ["120+ pieces", "Non-toxic colors", "Storage box", "Safe for kids"],
        inStock: true,
        badge: "Hot Deal"
    },
    {
        id: 11,
        name: "Kids Sport Shoes (Puma)",
        category: "Shoes",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
        price: 2499,
        originalPrice: 4999,
        rating: 4.6,
        reviews: 345,
        description: "Genuine Puma sport shoes for active kids.",
        features: ["Original Puma", "Comfortable fit", "Stylish design", "Sizes available"],
        inStock: true,
        badge: null
    },
    {
        id: 12,
        name: "Kids Reading Lamp",
        category: "Accessories",
        image: "https://images.unsplash.com/photo-1565636192335-14a6bc8c2eef?w=400&h=400&fit=crop",
        price: 1599,
        originalPrice: 2999,
        rating: 4.5,
        reviews: 187,
        description: "LED reading lamp for kids. Perfect for study time.",
        features: ["LED technology", "Adjustable brightness", "USB rechargeable", "Eye care"],
        inStock: true,
        badge: "New"
    }
];